INFO:2024-03-15 13:15:29,042:Closing down clientserver connection
INFO:2024-03-15 13:15:29,041:Closing down clientserver connection
INFO:2024-03-15 13:15:29,051:Closing down clientserver connection
INFO:2024-03-15 13:15:29,062:Closing down clientserver connection
INFO:2024-03-15 13:15:51,973:Closing down clientserver connection
INFO:2024-03-15 13:40:42,843:Closing down clientserver connection
INFO:2024-03-15 13:48:35,923:Closing down clientserver connection
INFO:2024-03-15 13:58:27,763:Closing down clientserver connection
INFO:2024-03-15 14:03:26,013:Closing down clientserver connection
INFO:2024-03-15 14:16:12,660:Closing down clientserver connection
INFO:2024-03-15 14:16:12,675:Closing down clientserver connection
INFO:2024-03-15 14:16:12,691:Closing down clientserver connection
INFO:2024-03-15 14:16:12,707:Closing down clientserver connection
INFO:2024-03-15 14:17:19,214:Error while sending or receiving.
Traceback (most recent call last):
  File "/home/caiafa/.cache/pypoetry/virtualenvs/pipeline-empresas-brasil-uj0UcSSs-py3.10/lib/python3.10/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
INFO:2024-03-15 14:17:19,217:Closing down clientserver connection
INFO:2024-03-15 14:17:19,218:Exception while sending command.
Traceback (most recent call last):
  File "/home/caiafa/.cache/pypoetry/virtualenvs/pipeline-empresas-brasil-uj0UcSSs-py3.10/lib/python3.10/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/caiafa/.cache/pypoetry/virtualenvs/pipeline-empresas-brasil-uj0UcSSs-py3.10/lib/python3.10/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/caiafa/.cache/pypoetry/virtualenvs/pipeline-empresas-brasil-uj0UcSSs-py3.10/lib/python3.10/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
INFO:2024-03-15 14:17:19,222:Closing down clientserver connection
INFO:2024-03-15 14:17:32,219:Closing down clientserver connection
INFO:2024-03-15 14:19:06,068:Closing down clientserver connection
INFO:2024-03-15 14:23:15,192:O arquivo Socios0.zip demorou 179.39370346069336 segundos para ser baixado.
INFO:2024-03-15 14:26:06,558:O arquivo Empresas0.zip demorou 350.7620301246643 segundos para ser baixado.
INFO:2024-03-15 14:29:07,111:Closing down clientserver connection
INFO:2024-03-15 14:29:07,118:Closing down clientserver connection
INFO:2024-03-15 14:29:07,126:Closing down clientserver connection
INFO:2024-03-15 14:29:07,134:Closing down clientserver connection
INFO:2024-03-15 14:31:14,229:Error while sending or receiving.
Traceback (most recent call last):
  File "/home/caiafa/.cache/pypoetry/virtualenvs/pipeline-empresas-brasil-uj0UcSSs-py3.10/lib/python3.10/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
INFO:2024-03-15 14:31:14,324:Closing down clientserver connection
INFO:2024-03-15 14:31:14,324:Exception while sending command.
Traceback (most recent call last):
  File "/home/caiafa/.cache/pypoetry/virtualenvs/pipeline-empresas-brasil-uj0UcSSs-py3.10/lib/python3.10/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/caiafa/.cache/pypoetry/virtualenvs/pipeline-empresas-brasil-uj0UcSSs-py3.10/lib/python3.10/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/caiafa/.cache/pypoetry/virtualenvs/pipeline-empresas-brasil-uj0UcSSs-py3.10/lib/python3.10/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
INFO:2024-03-15 14:31:14,360:Closing down clientserver connection
INFO:2024-03-15 14:31:27,446:Closing down clientserver connection
INFO:2024-03-15 14:36:47,923:Closing down clientserver connection
INFO:2024-03-15 14:36:47,939:Closing down clientserver connection
INFO:2024-03-15 14:36:47,954:Closing down clientserver connection
INFO:2024-03-15 14:36:47,969:Closing down clientserver connection
INFO:2024-03-15 14:38:25,477:Error while sending or receiving.
Traceback (most recent call last):
  File "/home/caiafa/.cache/pypoetry/virtualenvs/pipeline-empresas-brasil-uj0UcSSs-py3.10/lib/python3.10/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
INFO:2024-03-15 14:38:25,500:Closing down clientserver connection
INFO:2024-03-15 14:38:25,503:Exception while sending command.
Traceback (most recent call last):
  File "/home/caiafa/.cache/pypoetry/virtualenvs/pipeline-empresas-brasil-uj0UcSSs-py3.10/lib/python3.10/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/caiafa/.cache/pypoetry/virtualenvs/pipeline-empresas-brasil-uj0UcSSs-py3.10/lib/python3.10/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/caiafa/.cache/pypoetry/virtualenvs/pipeline-empresas-brasil-uj0UcSSs-py3.10/lib/python3.10/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
INFO:2024-03-15 14:38:25,511:Closing down clientserver connection
INFO:2024-03-15 14:39:43,281:Closing down clientserver connection
INFO:2024-03-15 15:46:36,258:O arquivo Socios0.zip demorou 178.90355610847473 segundos para ser baixado.
INFO:2024-03-15 15:50:28,184:O arquivo Empresas0.zip demorou 410.8292579650879 segundos para ser baixado.
INFO:2024-03-15 15:52:59,122:Closing down clientserver connection
INFO:2024-03-15 15:52:59,139:Closing down clientserver connection
INFO:2024-03-15 15:52:59,156:Closing down clientserver connection
INFO:2024-03-15 15:52:59,174:Closing down clientserver connection
INFO:2024-03-15 15:54:10,281:Error while sending or receiving.
Traceback (most recent call last):
  File "/home/caiafa/.cache/pypoetry/virtualenvs/pipeline-empresas-brasil-uj0UcSSs-py3.10/lib/python3.10/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
INFO:2024-03-15 15:54:10,287:Closing down clientserver connection
INFO:2024-03-15 15:54:10,288:Exception while sending command.
Traceback (most recent call last):
  File "/home/caiafa/.cache/pypoetry/virtualenvs/pipeline-empresas-brasil-uj0UcSSs-py3.10/lib/python3.10/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/caiafa/.cache/pypoetry/virtualenvs/pipeline-empresas-brasil-uj0UcSSs-py3.10/lib/python3.10/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/caiafa/.cache/pypoetry/virtualenvs/pipeline-empresas-brasil-uj0UcSSs-py3.10/lib/python3.10/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
INFO:2024-03-15 15:54:10,292:Closing down clientserver connection
INFO:2024-03-15 15:57:26,545:Closing down clientserver connection
INFO:2024-03-15 16:29:14,651:Closing down clientserver connection
